# Unsupported:
# pre-commit-hooks: https://github.com/dependabot/dependabot-core/issues/1524
# terraform's required_version: https://github.com/dependabot/dependabot-core/issues/8725
# tflint: https://github.com/dependabot/dependabot-core/issues/7515

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps)"
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
    open-pull-requests-limit: 1024 # A large value can be set to effectively remove the open pull request limit. # https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference#open-pull-requests-limit-
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      nix:
        patterns:
          - "*"
    labels:
      - "dependencies"
