version: "0.2"
language: en,nb
caseSensitive: true
# import:
#   - https://cdn.jsdelivr.net/npm/@cspell/dict-nb-no@latest/cspell-ext.json
# List of words to be always considered correct.
words:
  - githubusercontent
# cspell:disable
# List of flag words to be always considered incorrect.
# This is useful for offensive words and common spelling errors.
# For example "hte" should be "the".
flagWords:
  - hte
# cspell:enable
dictionaryDefinitions:
  - name: custom-words
    path: ./.cspell/custom-words.txt
    addWords: true
dictionaries:
  - custom-words
  - lorem-ipsum
  - companies
  - softwareTerms
  - bash
  - cpp
  - csharp
  - css
  - go
  - html
  - latex
  - node
  - php
  - powershell
  - python
  - typescript
  - fonts
languageSettings:
  - languageId: markdown
    locale: "*"
    caseSensitive: true
    patterns:
      - name: markdown-code-block
        pattern: >-
          /^(\s*```)[\s\S]*^\s*/gm
      - name: markdown-emoji
        pattern: >-
          /:[a-z_]+:/g
      - name: markdown-example-link
        pattern: >
          /([^\s]*\.)?example\.net\b/g

    ignoreRegExpList:
      - markdown-emoji
      - markdown-code-block
      - markdown-example-link
  - languageId: javascript
    caseSensitive: false
ignorePaths:
  - "node_modules/**"
  - "**/requirements.txt"
  - "**/*.svg"
  - "**/*.js"
useGitignore: true
features:
  weighted-suggestions: true
