## Flox Environment Manifest -----------------------------------------
##
##   _Everything_ you need to know about the _manifest_ is here:
##
##               https://flox.dev/docs/concepts/manifest
##
## -------------------------------------------------------------------
# Flox manifest version managed by Flox CLI
version = 1


## Install Packages --------------------------------------------------
##  $ flox install gum  <- puts a package in [install] section below
##  $ flox search gum   <- search for a package
##  $ flox show gum     <- show all versions of a package
## -------------------------------------------------------------------
[install]
# keep-sorted start
age.pkg-path = "age"
cabal-install.pkg-path = "cabal-install"
ghc.pkg-path = "ghc"
gnugrep.pkg-path = "gnugrep"
gnused.pkg-path = "gnused"
nixd.pkg-path = "nixd"
nixfmt-rfc-style.pkg-path = "nixfmt-rfc-style"
nixfmt-tree.pkg-path = "nixfmt-tree"
pre-commit.pkg-path = "pre-commit"
update-nix-fetchgit.pkg-path = "update-nix-fetchgit"
uutils-coreutils-noprefix.pkg-path = "uutils-coreutils-noprefix"
uutils-diffutils.pkg-path = "uutils-diffutils"
uutils-findutils.pkg-path = "uutils-findutils"
# gum.pkg-path = "gum"
# gum.version = "^0.14.5"
# keep-sorted end

## Environment Variables ---------------------------------------------
##  ... available for use in the activated environment
##      as well as [hook], [profile] scripts and [services] below.
## -------------------------------------------------------------------
[vars]
# INTRO_MESSAGE = "It's gettin' Flox in here"

## Activation Hook ---------------------------------------------------
##  ... run by _bash_ shell when you run 'flox activate'.
## -------------------------------------------------------------------
[hook]
on-activate = """
  echo ""
  echo "🚀 Activating Flox environment...."
  echo "Flox '$(flox --version)' located in '$(which flox)'."
  echo "Nix '$(nix --version | awk '{print $3}')' located in '$(which nix)'."
  # keep-sorted start
  echo "Age '$(age --version)' located in '$(which age)'."
  echo "Cabal '$(cabal --version | head --lines 1 | awk '{print $3}')' located in '$(which cabal)'."
  echo "Cp '$(cp --version | awk '{print $2}')' located in '$(which cp)'."
  echo "Diff '$(diff --version | head --lines 1 | awk '{print $4}')' located in '$(which diff)'."
  echo "Find '$(find --version | awk '{print $3}')' located in '$(which find)'."
  echo "GHC '$(ghc --version | awk '{print $8}')' located in '$(which ghc)'."
  echo "GnuGrep '$(grep --version | head --lines 1 | awk '{print $4}')' located in '$(which grep)'."
  echo "GnuSed '$(sed --version | head --lines 1 | awk '{print $4}')' located in '$(which sed)'."
  echo "Pre-commit '$(pre-commit --version | awk '{print $2}' )' located in '$(which pre-commit)'."
  # keep-sorted end
  echo ""
"""
# on-activate = '''
#   # -> Set variables, create files and directories
#   # -> Perform initialization steps, e.g. create a python venv
#   # -> Useful environment variables:
#   #      - FLOX_ENV_PROJECT=/home/user/example
#   #      - FLOX_ENV=/home/user/example/.flox/run
#   #      - FLOX_ENV_CACHE=/home/user/example/.flox/cache
# '''


## Profile script ----------------------------------------------------
## ... sourced by _your shell_ when you run 'flox activate'.
## -------------------------------------------------------------------
[profile]
# common = '''
#   gum style \
#   --foreground 212 --border-foreground 212 --border double \
#   --align center --width 50 --margin "1 2" --padding "2 4" \
#     $INTRO_MESSAGE
# '''
## Shell specific profiles go here:
# bash = ...
# zsh  = ...
# fish = ...


## Services ----------------------------------------------------------
##  $ flox services start             <- Starts all services
##  $ flox services status            <- Status of running services
##  $ flox activate --start-services  <- Activates & starts all
## -------------------------------------------------------------------
[services]
# myservice.command = "python3 -m http.server"


## Other Environment Options -----------------------------------------
[options]
# Systems that environment is compatible with
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
# Uncomment to disable CUDA detection.
# cuda-detection = false
