jobs:
  nix-flake-check:
    name: nix-flake-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: determinatesystems/nix-installer-action@main
      - run: |
          echo "Version: \`$(nix --version)\`" | tee --append ${GITHUB_STEP_SUMMARY}
      - run: |
          echo "$(nix --experimental-features "nix-command flakes" flake check)" \
          | tee --append ${GITHUB_STEP_SUMMARY}
on:
  pull_request:
  push:
    branches: [main]
