jobs:
  show-nix-info:
    name: show-nix-info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: determinatesystems/nix-installer-action@main
      - run: |
          echo "Version: \`$(nix --version)\`" \
          | tee --append ${GITHUB_STEP_SUMMARY}
      - run: |
          printf '\n<details><summary>Nix-Info</summary>\n<p>\n\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          echo $(nix-shell \
            --packages nix-info \
            --run 'nix-info --markdown --sandbox --host-os') \
            | tee --append nix-info.txt
          cat nix-info.txt \
            | tee --append ${GITHUB_STEP_SUMMARY}
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
      - run: |
          printf '\n<details><summary>Nix-Configuration</summary>\n<p>\n\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          echo $(sudo cat /etc/nix/nix.conf) \
            | tee --append nix-configuration.txt
          cat nix-configuration.txt \
            | tee --append ${GITHUB_STEP_SUMMARY}
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
      - run: |
          printf '\n<details><summary>Nix-Instaler-Version</summary>\n<p>\n\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          echo $(/nix/nix-installer --version) \
            | tee --append nix-installer-version.txt
          cat installer-version.txt \
            | tee --append ${GITHUB_STEP_SUMMARY}
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
on:
  pull_request:
  push:
    branches: [main]
