on:
  pull_request:
  push:
    branches: [main]

jobs:
  show-nix-info:
    name: show-nix-info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          echo "$(nix --version)" | tee --append ${GITHUB_STEP_SUMMARY}
      - run: |
          echo "Nixpkgs Version: $(nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version' | tr -d '"')" | tee --append ${GITHUB_STEP_SUMMARY}
          echo "NixOS Version: $(nix-instantiate --eval -E '(import <nixpkgs> {}).lib.nixosVersion' | tr -d '"')" | tee --append ${GITHUB_STEP_SUMMARY}
          echo "$(nix-shell \
            --packages nix-info \
            --run "nix-info --markdown --sandbox --host-os)" | tee --append ${GITHUB_STEP_SUMMARY}
