on:
  pull_request:
  push:
    branches: [main]

jobs:
  show-nix-info:
    name: show-nix-info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          echo "Nix Version: $(nix --version)" | tee --append ${GITHUB_STEP_SUMMARY}
      - run: |
          nix-shell \
            --packages nix-info \
            --run "nix-info --markdown --sandbox --host-os"
