name: Show Nix Info

on:
  push:
    branches:
      - "unstable"
      - "main"
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.sha }}"
  cancel-in-progress: true

permissions: {}

jobs:
  show-nix-info:
    name: show-nix-info
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
        with:
          summarize: false
      - name: Setup GitHub Actions Cache
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14
        with:
          use-gha-cache: "enabled"
          use-flakehub: "disabled"
      - run: |
          echo "Version: (\`nix --version\`): $(nix --version)" \
          | tee --append "${GITHUB_STEP_SUMMARY}"
      - run: |
          printf "\n<details open><summary>Nix-Info: (<code>nix-shell --packages nix-info --run 'nix-info --markdown --sandbox --host-os'</code>)</summary>\n<p>\n\n" | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          nix-shell --packages nix-info --run 'nix-info --markdown --sandbox --host-os' | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '</p></details>\n' | tee --append "${GITHUB_STEP_SUMMARY}"
      - run: |
          printf "\n<details open><summary>Nix-Configuration: (<code>sudo cat /etc/nix/nix.conf</code>)</summary>\n<p>\n\n" | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          sudo cat /etc/nix/nix.conf | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '</p></details>\n' | tee --append "${GITHUB_STEP_SUMMARY}"
      - run: |-
          echo "Nix-Installer-Version: (\`/nix/nix-installer --version\`): $(/nix/nix-installer --version)" \
          | tee --append "${GITHUB_STEP_SUMMARY}"
