jobs:
  show-nix-info:
    name: show-nix-info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: determinatesystems/nix-installer-action@main
      - run: |
          echo "Version: \`$(nix --version)\`" \
          | tee --append ${GITHUB_STEP_SUMMARY}
      - run: |
          printf '\n<details open><summary>Nix-Info</summary>\n<p>\n\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          nix-shell --packages nix-info --run 'nix-info --markdown --sandbox --host-os' | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '</p></details>\n' | tee --append "${GITHUB_STEP_SUMMARY}"
      - run: |
          printf '\n<details open><summary>Nix-Configuration</summary>\n<p>\n\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          sudo cat /etc/nix/nix.conf | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '</p></details>\n' | tee --append "${GITHUB_STEP_SUMMARY}"
      - run: |
          printf '\n<details open><summary>Nix-Installer-Version</summary>\n<p>\n\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          /nix/nix-installer --version | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '```\n' | tee --append "${GITHUB_STEP_SUMMARY}"
          printf '</p></details>\n' | tee --append "${GITHUB_STEP_SUMMARY}"
on:
  pull_request:
  push:
    branches: [main]
