jobs:
  show-nix-info:
    name: show-nix-info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: determinatesystems/nix-installer-action@main
      - run: |
          echo "Version: \`$(nix --version)\`" \
          | tee --append ${GITHUB_STEP_SUMMARY}
      - run: |
          echo "Nix-Info: \`$(nix-shell \
            --packages nix-info \
            --run 'nix-info --markdown --sandbox --host-os')\`" \
            | tee --append ${GITHUB_STEP_SUMMARY}
      - run: |
          echo "Nix-Configuration: `$(sudo cat /etc/nix/nix.conf)\`" \
          | tee --append ${GITHUB_STEP_SUMMARY}
      - run: |
          echo "Nix-Instaler-Version: \`$(/nix/nix-installer --version)\`" \
          | tee --append ${GITHUB_STEP_SUMMARY}
on:
  pull_request:
  push:
    branches: [main]
