name: Switch Nix

on:
  # push:
  #   branches:
  #     - unstable
  #     - main
  # pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.sha }}"
  cancel-in-progress: true

permissions: {}

jobs:
  switch-nix:
    name: switch-nix
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: determinatesystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - run: |
          echo "Version: \`$(nix --version)\`" \
          | tee --append "${GITHUB_STEP_SUMMARY}"
      - run: |
          nix-shell --packages nix-info --run 'nix-info --markdown --sandbox --host-os' \
          | tee --append "${GITHUB_STEP_SUMMARY}"
      - run: |
          nix --experimental-features "nix-command flakes" flake check \
          | tee --append "${GITHUB_STEP_SUMMARY}"
      - run: |
          nix flake check \
          | tee --append "${GITHUB_STEP_SUMMARY}"
      - run: |-
          nix run github:ryanccn/morlana -- switch --flake . \
          | tee --append "${GITHUB_STEP_SUMMARY}"
