name: "Thaw"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: determinatesystems/nix-installer-action@main
      - uses: snowfallorg/thaw-action@main
