name: Trivy

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # “At 00:00 on Sunday.”
  workflow_dispatch:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Run Trivy security scan
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # v0.33.1
        with:
          scan-type: "fs"
          scan-ref: "."
          trivy-config: trivy.yaml

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@fdbfb4d2750291e159f0156def62b853c2798ca2 # v4.31.5
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

      - name: Generate summary report
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # v0.33.1
        with:
          scan-type: "fs"
          scan-ref: "."
          trivy-config: trivy.yaml
          format: "table"
          skip-setup-trivy: true
