name: Validate Renovate Configuration

on:
  push:
    branches:
      - unstable
      - main
    paths: &paths
      - .github/workflows/validate-renovate-configuration.yaml
      - renovate.json
      - renovate.json5
      - .github/renovate.json
      - .github/renovate.json5
      - .gitlab/renovate.json
      - .gitlab/renovate.json5
      - .renovaterc
      - .renovaterc.json
      - .renovaterc.json5
  pull_request:
    paths: *paths
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  validate:
    name: Validate
    timeout-minutes: 3
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Mask Tokens
        run: echo "::add-mask::${{ github.token }}"
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Nix
        uses: determinatesystems/determinate-nix-action@8d87e8d5e5b8a8309d4281094560f127d9a265f1 # v3.22.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          trust-runner-user: true
          summarize: true
      - name: Validate Renovate Configuration
        run: |-
          nix shell nixpkgs#renovate --command renovate-config-validator --strict
