jobs:
  virtual-machines-integration-tests:
    name: virtual-machines-integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Enable KVM Group Permissions
        run: |
          # spell-checker: disable
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' \
            | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          # spell-checker: enable
      - run: |
          nix-build minimal-machine-test.nix
        working-directory: learn/virtual-machines-integration-tests
      - run: |
          nix-build client-server-test.nix
        working-directory: learn/virtual-machines-integration-tests
on:
  workflow_dispatch:
