on:
  workflow_dispatch:

permissions: {}

jobs:
  virtual-machines-integration-tests:
    name: virtual-machines-integration-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: determinatesystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
      - name: Enable KVM Group Permissions
        run: |
          # spell-checker: disable
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' \
            | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          # spell-checker: enable
      - run: |
          nix-build minimal-machine-test.nix
        working-directory: learn/virtual-machines-integration-tests
      - run: |
          nix-build client-server-test.nix
        working-directory: learn/virtual-machines-integration-tests
