#!/usr/bin/env sh

# https://github.com/felixkratz/dotfiles/blob/e27673f07ff41eb6a4816daabb79b0a5e837a105/.config/yabai/yabairc

sudo yabai --load-sa --verbose

yabai --message signal --add event=dock_did_restart action="sudo yabai --load-sa --verbose"

yabai --message config mouse_follows_focus off
yabai --message config focus_follows_mouse off
yabai --message config window_zoom_persist off
yabai --message config window_placement second_child
yabai --message config window_shadow float
yabai --message config window_opacity on
yabai --message config window_opacity_duration 0.2
yabai --message config active_window_opacity 1.0
yabai --message config normal_window_opacity 0.8
yabai --message config window_animation_duration 0.5
yabai --message config window_animation_easing ease_out_quint
yabai --message config insert_feedback_color 0xff9dd274
yabai --message config split_ratio 0.50
yabai --message config auto_balance off
yabai --message config auto_padding on
yabai --message config mouse_modifier fn
yabai --message config mouse_action1 move
yabai --message config mouse_action2 resize
yabai --message config mouse_drop_action swap

yabai --message config top_padding 8
yabai --message config bottom_padding 8
yabai --message config left_padding 8
yabai --message config right_padding 8
yabai --message config window_gap 4

# yabai --message config external_bar all:40:0
yabai --message config debug_output on # https://github.com/koekeishiya/yabai/blob/f4ada8d557aeb9c8ba0d031ee6f645acffff50fd/doc/yabai.asciidoc#L137

# Exclude problematic apps from being managed:
yabai --message rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai --message rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai --message rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai --message rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai --message rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai --message rule --add app="^Google Chrome|Firefox$" space=1
yabai --message rule --add app="^(Code|RStudio)$" space=2

# https://github.com/jiangtao/mydotfiles/blob/3164aac81246719440c33cd8bc9975f784fd7f58/ln/.yabairc
ideAps="^(IntelliJ IDEA|RubyMine|PyCharm|DataGrip|Toolbox)$"
disableApps="^(JetBrains Toolbox|Spotify|Amazon Music|Preferences|Slack|WhatsApp|Microsoft Teams|DeepL|系统偏好设置|提醒事项|关于本机|音乐|SpaceLauncher|licecap)$"

yabai --message rule --add app="${ideAps}" space=3 manage=off
yabai --message rule --add app="${disableApps}" manage=off
yabai --message rule --add app="^(Alacritty|iTerm)$" space=4

# https://github.com/felixkratz/jankyborders?tab=readme-ov-file#bootstrap-with-yabai
borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

yabai --message config layout bsp

echo "yabai configuration loaded..."
